import { chromium } from '/tmp/claude-0/-home-user-Sam-City-2026/6309cccc-23e7-5301-8e65-4b7cab65a79b/scratchpad/node_modules/playwright-core/index.mjs';
const S = '/tmp/claude-0/-home-user-Sam-City-2026/6309cccc-23e7-5301-8e65-4b7cab65a79b/scratchpad/';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 760 } }); const logs = []; p.on('pageerror', (e) => logs.push('PAGEERROR: ' + e.stack));
await p.goto('http://localhost:8123/index.html?auto&demo&scale=0.5&noraids'); await p.waitForTimeout(900);
const ev = (f, a) => p.evaluate(f, a);
console.log(await ev(() => { const g = window.__game; g.favours.timer = 0; g.favours.update(0.1); const f = g.favours.list[0]; if (!f) return 'no favour'; const s = f.sim; g.setMode('sim'); g.player.teleport(s.x + 1, s.z); g.startDialogue(s); window.__f = f; return `${s.name} favour ${f.n} ${f.mat}`; }));
await p.waitForTimeout(300); console.log('ask:', await ev(() => window.__game.ui.dialogue.lines.join(' / ')));
await ev(() => { const g = window.__game, f = window.__f; g.player.inv = { [f.mat]: f.n + 1 }; g.ui.closeDialogue(); g.startDialogue(f.sim); }); await p.waitForTimeout(200);
console.log('give:', await ev(() => window.__game.ui.dialogue.lines.join(' / ')), 'left', await ev(() => window.__game.favours.list.length), 'inv', await ev(() => window.__game.player.invText()));
await p.screenshot({ path: S + 'fav.png' });
console.log(logs.join('\n')); await b.close();
