// node tools/round14.mjs -> workers stay at work in work hours, visitors leave after their stops, people visible through an open door
import { chromium } from '/tmp/claude-0/-home-user-Sam-City-2026/6309cccc-23e7-5301-8e65-4b7cab65a79b/scratchpad/node_modules/playwright-core/index.mjs';
const S = '/tmp/claude-0/-home-user-Sam-City-2026/6309cccc-23e7-5301-8e65-4b7cab65a79b/scratchpad/';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 760 } }); const logs = []; p.on('pageerror', (e) => logs.push('PAGEERROR: ' + e.stack));
await p.goto('http://localhost:8123/index.html?auto&demo&scale=0.5&noraids'); await p.waitForTimeout(1000);
const ev = (f, a) => p.evaluate(f, a);
console.log('workers', await ev(() => { const g = window.__game; g.clock.hour = 8.5; g.advance(20); let at = 0, eat = 0, n = 0;
  for (let k = 0; k < 120; k++) { g.advance(1); if (g.clock.hour < 9.5 || g.clock.hour > 16) continue; for (const s of g.population.sims) { if (!s.workplace || s.kind !== 'resident') continue; n++; if (s.activity === 'work' && (s.inside === s.workplace || Math.hypot(s.x - s.workplace.cx, s.z - s.workplace.cz) < s.workplace.w * 3)) at++; if (s.activity === 'eat') eat++; } }
  return `at their job ${(100 * at / n).toFixed(0)}%, off eating ${(100 * eat / n).toFixed(0)}%  (${g.clock.hhmm})`; }));
console.log('visitors', await ev(() => { const g = window.__game; g.clock.hour = 10; const made = []; for (let i = 0; i < 3; i++) { g.population.visitorTimer = 0; g.population.update(0.1); } const V0 = g.population.sims.filter((s) => s.kind === 'visitor'); for (const v of V0) v.visits = 5; for (let k = 0; k < 200; k++) g.advance(1); const left = V0.filter((v) => v.remove || !g.population.sims.includes(v)).length; return `${V0.length} visitors done sightseeing, ${left} have gone home; still here: ` + V0.filter((v) => g.population.sims.includes(v)).map((v) => `${v.activity}/${v.phase}/${v.inside ? v.inside.def.name : '-'}/path${v.path.length}`).join(', '); }));
console.log('see in', await ev(() => { const g = window.__game; g.clock.hour = 11; g.advance(5); const h = g.buildings.list.filter((b) => b.ext && b.ext.doors && b.ext.doors.length && !b.def.large).sort((a, c) => g.population.sims.filter((s) => s.inside === c).length - g.population.sims.filter((s) => s.inside === a).length)[0]; g.setMode('sim'); const a = h.rot * Math.PI / 2; g.player.teleport(h.doorOut.x + Math.sin(a) * 4, h.doorOut.z + Math.cos(a) * 4); g.player.yaw = a; g.player.third = true; g.player.pitch = -0.1; window.__h = h;
  const inside = () => g.population.sims.filter((s) => s.inside === h); for (let i = 0; i < 5; i++) g.update(0.05); const shut = inside().filter((s) => s.mesh.visible).length; h.doorHeld = true; for (let i = 0; i < 20; i++) g.update(0.05); const open = inside().filter((s) => s.mesh.visible).length; return `${inside().length} inside: visible with door shut ${shut}, door open ${open}`; }));
await p.waitForTimeout(800); await p.screenshot({ path: S + 'r14_door.png' });
console.log(logs.join('\n')); await b.close();
